version: '2'
services:
    teamdb:
        container_name: teamdb
        build:
            # all paths are relative to the location of docker-compose.yml
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            # Modify the first param of the line below with
            # the location of your application when developing
            - ./:/var/www
